Mw:
  Metamorph:
    transformations:
      extensionInventory:
        name: ExtensionInventory
        position: 10
      classInventory:
        name: ClassInventory
        position: 20
        settings:
          visitors: []
      resourceInventory:
        name: ResourceInventory
        position: after classInventory
      cleanupPackages:
        name: CleanupPackages
        position: 30
      createPackages:
        name: CreatePackages
        position: 40
      createClasses:
        name: CreateClasses
        position: 50
      createResources:
        name: CreateResources
        position: 55
      rewritePackageClasses:
        name: PackageClassRewrite
        position: 60
        settings:
          visitors:
            - ClassNamespaceRewriterVisitor
      analyzeClasses:
        name: AnalyzeClasses
        position: 70
      refactorClasses:
        name: PackageClassRewrite
        position: 80
        settings:
          visitors:
            - ExtbaseClassReplacementVisitor
            - ExtbaseClassEliminationVisitor
            - ReplaceMakeInstanceCallsVisitor
            - RewriteSingletonsVisitor
            - ReplaceAnnotationsVisitor
            - InjectUtilitiesVisitor
            - FlashMessageVisitor
            - PackageRedirectVisitor
      transformLocallang:
        name: XliffConversion
        position: 90
      migrateDatabase:
        name: MigrateDatabaseStructure
        position: 100
      createDoctrineMigrations:
        name: CreateDoctrineMigrations
        position: 110
    staticReplacements:
      TYPO3\CMS\Extbase\Mvc\Controller\ActionController: TYPO3\Flow\Mvc\Controller\ActionController
      TYPO3\CMS\Core\Utility\GeneralUtility: Mw\T3Compat\Utility\GeneralUtility
      TYPO3\CMS\Fluid\Core\ViewHelper\AbstractViewHelper: TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper
      TYPO3\CMS\Fluid\ViewHelpers\IfViewHelper: TYPO3\Fluid\ViewHelpers\IfViewHelper
      TYPO3\CMS\Extbase\Persistence\ObjectStorage: Doctrine\Common\Collections\Collection
      TYPO3\CMS\Extbase\Persistence\QueryInterface: TYPO3\Flow\Persistence\QueryInterface
      TYPO3\CMS\Extbase\Persistence\Repository: TYPO3\Flow\Persistence\Repository
      TYPO3\CMS\Extbase\Domain\Model\FrontendUser: Mw\T3Compat\Domain\Model\FrontendUser
      TYPO3\CMS\Extbase\Domain\Model\FrontendUserGroup: Mw\T3Compat\Domain\Model\FrontendUserGroup
      TYPO3\CMS\Extbase\Domain\Repository\FrontendUserRepository: Mw\T3Compat\Domain\Repository\FrontendUserRepository
      TYPO3\CMS\Extbase\Domain\Repository\FrontendUserGroupRepository: Mw\T3Compat\Domain\Repository\FrontendUserGroupRepository
      TYPO3\CMS\Extbase\Tests\Unit\BaseTestCase: TYPO3\Flow\Tests\UnitTestCase
      TYPO3\CMS\Extbase\Validation\Validator\AbstractValidator: TYPO3\Flow\Validation\Validator\AbstractValidator
      Tx_Extbase_Mvc_Controller_ActionController: TYPO3\Flow\Mvc\Controller\ActionController
      Tx_Fluid_Core_ViewHelper_AbstractViewHelper: TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper
      Tx_Fluid_ViewHelpers_IfViewHelper: TYPO3\Fluid\ViewHelpers\IfViewHelper
      Tx_Extbase_Persistence_ObjectStorage: Doctrine\Common\Collections\Collection
      Tx_Extbase_Persistence_QueryInterface: TYPO3\Flow\Persistence\QueryInterface
      Tx_Extbase_Persistence_Repository: TYPO3\Flow\Persistence\Repository
      Tx_Extbase_Domain_Model_FrontendUser: Mw\T3Compat\Domain\Model\FrontendUser
      Tx_Extbase_Domain_Model_FrontendUserGroup: Mw\T3Compat\Domain\Model\FrontendUserGroup
      Tx_Extbase_Domain_Repository_FrontendUserRepository: Mw\T3Compat\Domain\Repository\FrontendUserRepository
      Tx_Extbase_Domain_Repository_FrontendUserGroupRepository: Mw\T3Compat\Domain\Repository\FrontendUserGroupRepository
      Tx_Extbase_Tests_Unit_BaseTestCase: TYPO3\Flow\Tests\UnitTestCase
      Tx_Extbase_Validation_Validator_AbstractValidator: TYPO3\Flow\Validation\Validator\AbstractValidator
      t3lib_div: Mw\T3Compat\Utility\GeneralUtility
    resourceExtensions:
      templates: {targetPath: Private/Templates, extensions: [html, htm]}
      languageFiles: {targetPath: Private/Language, extensions: [xml, xlf]}
      images: {targetPath: Public/Images, extensions: [jpeg, jpg, gif, tif, svg, eps, png]}
      javascript: {targetPath: Public/JavaScript, extensions: [js, coffee, ts]}
      css: {targetPath: Public/Stylesheets, extensions: [css, sass, less, scss]}
    classNameStrategies:
      extbase:
        name: ExtbaseNamespacedConversionStrategy
        position: 10
      extbaseLegacy:
        name: ExtbaseLegacyConversionStrategy
        position: after extbase
      pibase:
        name: PibasePluginConversionStrategy
        position: after extbaseLegacy
      generic:
        name: GenericConversionStrategy
        position: end

TYPO3:
  Flow:
    object:
      excludeClasses:
        'nikic.phpparser': ['PhpParser\\.*']
